name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: /var/lib/apt
        key: apt-cache-v2
        restore-keys: |
          apt-cache-v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
                             curl \
                             bzip2 \
                             unzip \
                             ca-certificates \
                             dvipng \
                             texlive-fonts-recommended \
                             texlive-fonts-extra \
                             texlive-latex-extra \
                             fonts-freefont-ttf \
                             cm-super

    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: /usr/local/share/fonts/LibreFranklin
        key: fonts-v3
        restore-keys: |
          fonts-v3
    - name: Install Libre Franklin Open Type
      run: |
        if [[ ! -d /usr/local/share/fonts/LibreFranklin ]]; then
          curl -sSL "https://fonts.google.com/download?family=Libre%20Franklin" -o /tmp/LibreFranklin.zip
          sudo mkdir -p /usr/local/share/fonts/LibreFranklin
          pushd /usr/local/share/fonts/LibreFranklin
          sudo unzip -e /tmp/LibreFranklin.zip
          sudo chmod 755 /usr/local/share/fonts/LibreFranklin
          find /usr/local/share/fonts/LibreFranklin -type d -exec sudo chmod 755 -- {} +
          find /usr/local/share/fonts/LibreFranklin -type f -exec sudo chmod 744 -- {} +
        fi
        fc-cache -v

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the page
    - name: Build the book
      run: |
        export PATH=$ANTSPATH:$PATH
        jupyter-book build docs

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
